### ISSUE TITLE
朋友，actix作者疑似跑路，框架是不是得考虑换换了

### ISSUE THREAD

**Issue by luojia65** [arlicle/panda-api#1]
rt，建议rocket或hyper

**Comment by arlicle** [comment]
😂没有跑路，只是闹一点情绪，已经有人组织了团队会参与actix维护了。后续我想我能力足够的话也会加入维护。actix设计的非常好，简单、易用、强大，非常符合我的要求。过年假期我研究一下rocket 和hyper，谢谢

**Comment by luojia65** [comment]
感觉靠不住，他github项目已经没有再更新了，里面还是他的声明。怀疑没找到人继续维护

**Comment by arlicle** [comment]
观察一段时间:)

**Comment by arlicle** [comment]
@luojia65 Actix-web 项目已回归 ✌️ 
[https://github.com/actix/actix-web/issues/1289](https://github.com/actix/actix-web/issues/1289)
