### ISSUE TITLE
README 里补充源码安装方法以及一些其他使用建议

### ISSUE THREAD

**Issue by Piping** [arlicle/panda-api#3]
1. 使用下载的Linux安装包，直接在解压的目录里运行`./panda`， 无法加载网页内容。（使用安装命令以后可以）。希望能添加无需安装的运行方式以及源码编译运行的命令。

2. 将 `-h` 和 `--help` 留给使用说明。

**Comment by arlicle** [comment]
你好，你直接解压后运行`./panda`，无法加载网页内容是因为没有复制对应皮肤文件到`~/.panda_api/theme`目录，因为是在线浏览文档服务是，前后端分离开发的，皮肤文件是单独的前端模板文件，目前暂时还没有计划把皮肤文件一起编译到panda文件中。

`install`安装做的只是只是把 `panda`和`theme`复制到`~/.panda_api/`文件目录，并修改相关`bash`配置文件

然后直接编译运行是可以的，也可以直接请求访问服务，区别只是：如果你执行安装过，那么就能在线浏览文档；没有安装过，`~/.panda_api/theme`没有前端文件，那么就无法在线浏览文档。

好的，谢谢你的建议。我稍后把源码安装 和自定义安装的方法加进去:)

**Comment by arlicle** [comment]
对了 更多使用说明在这里

### Panda Api 如何使用
- [快速简单的写好第一个接口文档 使用说明(一)](https://www.debugmyself.com/p/2020/1/15/Panda-api%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E/)
- [接口文档的高级配置 使用说明(二)](https://www.debugmyself.com/p/2020/1/15/Panda-api%E9%AB%98%E7%BA%A7%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E/)
- [相关字段说明](https://www.debugmyself.com/p/2020/1/29/Panda-api%E5%AD%97%E6%AE%B5%E8%AF%B4%E6%98%8E/)
- [test_data使用说明](https://www.debugmyself.com/p/2020/1/27/Panda-api-test_data%E5%8C%B9%E9%85%8D%E8%AF%B4%E6%98%8E/)
- [Auth接口权限配置说明](https://www.debugmyself.com/p/2020/2/2/Panda-api接口权限配置说明/)

**Comment by Piping** [comment]
1. 希望用脚本提供自定义安装路径前缀，以及用脚本而不是二进制进行安装。如果把应用打包进发行版里，一般会把应用的额外文件装在 类似 `/usr/share/pandaAPI/` 。个人安装的时候放在 `/usr/local/share/pandaAPI/`里。然后二进制文件放在 `/usr/bin/` 里。

2. 希望能支持搜索不同的位置的前端主题文件。比如panda程序文件地址，当前工作目录，全局目录`/usr/local/share` 这样的顺序。

**Comment by arlicle** [comment]
@Piping 👍👍👍第一点,非常好的建议,谢谢你的建议,  第二点我没有明白是什么意思

**Comment by cxlthxx** [comment]
为什么在linux下安装完install 后无法使用panda命令 这个是如何开启的

**Comment by arlicle** [comment]
@cxlthxx 如果命令没有生效，那么如果用的是bash，在终端执行命令：`souce ~/.bashrc`，如果是zsh，那么在终端执行`souce ~/zshrc`。

或者关闭终端，重新打开一个终端再执行就可以了。
更多请看使用说明：[https://www.debugmyself.com/p/2020/1/15/Panda-api%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E/](https://www.debugmyself.com/p/2020/1/15/Panda-api%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E/)

**Comment by Piping** [comment]
@arlicle 第二点说的是前端web文件位置。现在放在`~/.panda_api/`. 希望程序可以搜索当前工作目录，全局目录/usr/local/share 来寻找这些前端web文件。

**Comment by arlicle** [comment]
@Piping 明白了，谢谢。👍👍 后续版本里面我针对 Linux，Mac，Windows分别处理这个问题;)
