### ISSUE TITLE
执行cargo run发生错误

### ISSUE THREAD

**Issue by adminSxs** [arlicle/panda-api#7]
INFO  actix_server::builder > Starting 32 workers
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 28, kind: Other, message: "No space left on device" })', src/libcore/result.rs:1188:5
stack backtrace:
 INFO  actix_server::builder > Starting "actix-web-service-0.0.0.0:8081" service on 0.0.0.0:8081
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1188
  14: core::result::Result<T,E>::unwrap
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/result.rs:956
  15: panda_api::utils::watch_api_docs_change::{{closure}}
             at src/utils.rs:22
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by arlicle** [comment]
你好，报的错是：`"No space left on device" `请检查你编译目录是否有足够的硬盘空间

**Comment by arlicle** [comment]
请问你的问题解决了吗？我关闭这个Issue了哦
