### ISSUE TITLE
关于 test_data 模拟数组返回只返回了单个对象

### ISSUE THREAD

**Issue by zhaiyongtao** [arlicle/panda-api#8]
![image](https://user-images.githubusercontent.com/22289034/75624426-eaed8480-5bee-11ea-80a9-e377d3e76082.png)

代码如下:
![image](https://user-images.githubusercontent.com/22289034/75624433-fe005480-5bee-11ea-8c8c-bbabb5f7c8ea.png)

**Comment by arlicle** [comment]
收到 Bug已解决，一会就发布新的版本:)

**Comment by arlicle** [comment]
已发布，请下载最新0.7.3版本:) [https://github.com/arlicle/panda-api/releases/latest](https://github.com/arlicle/panda-api/releases/latest)
