### ISSUE TITLE
源码无法构建

### ISSUE THREAD

**Issue by gdtdpt** [arlicle/panda-api#9]
你好，我执行`cargo run`无法正确构建项目

我的环境如下：
rustc 1.41.1 (f3e1a954d 2020-02-24)
rustup 1.21.1 (7832b2ebe 2019-12-20)
cargo 1.41.0 (626f0f40e 2019-12-03)

rustup show
Default host: x86_64-apple-darwin

我执行`cargo run `出现以下错误:
   Compiling failure_derive v0.1.6
   Compiling serde_json v1.0.48
   Compiling serde_urlencoded v0.6.1
   Compiling actix-router v0.2.4
error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> /Users/xuexi/.cargo/registry/src/github.com-1ecc6299db9ec823/failure_derive-0.1.6/src/lib.rs:107:70
    |
107 | fn display_body(s: &synstructure::Structure) -> Result<Option<quote::__rt::TokenStream>, Error> {
    |                                                                      ^^^^ could not find `__rt` in `quote`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `failure_derive`.
warning: build failed, waiting for other jobs to finish...
error: build failed

是我的环境问题吗？我对rust了解不是很多，希望能得到帮助，谢谢。

**Comment by arlicle** [comment]
你好，不好意思，这几天有点忙。我更新到了你的环境，所有环境和你都是一样的。但是编译没有发生报错。请问你用的是哪里的源？

**Comment by gdtdpt** [comment]
@arlicle 你好，感谢你的回复。
我试过官方默认源和ustc源，也试过把`~/.cargo/registry/src/`下的依赖都删除重新下载，依然会出现同样的错误。

**Comment by arlicle** [comment]
你全部使用官方源试试看，去掉ustc

**Comment by gdtdpt** [comment]
@arlicle 你好，能打包了，我也不太清楚发生了什么。我新建一个项目，把panda-api的依赖复制到新项目中是没问题的。然后把panda-api中的Cargo.lock删掉再执行`cargo run `就没有上面的问题了。谢谢你的帮助。
